---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${MYSQL_CLAIM}
  labels:
    app: ${APP}
    tier: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi