---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-${APP}
  labels:
    app: ${APP}
spec:
  selector:
    matchLabels:
      app: ${APP}
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${APP}
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: sqlpass
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        ports:
        - containerPort: ${MYSQL_PORT}
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          limits:
            memory: "6Gi"
            cpu: "700m"
          requests:
            memory: "5Gi"
            cpu: "500m"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: ${MYSQL_CLAIM}
