---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${WP_PV_NAME}
spec:
  capacity:
    storage: ${WP_DISK_SIZE}Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /pvcs/${WP_DIR_NAME}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "k8s-node-2"
          - "k8s-node-3"
